/**
 * Settlement System - Redesigned for Multiplayer Wager Collection
 * 
 * Flow:
 * 1. Host publishes settlement event with net payments (no invoices required)
 * 2. Recipients query for settlements where they are owed money
 * 3. Recipients generate invoices and publish settlement-claim events
 * 4. Payers see claims, pay invoices, and publish payment-proof events
 */

import type { NostrEvent } from '@nostrify/nostrify';

/**
 * Net payment from one player to another
 */
export interface SettlementPayment {
  from: string;           // Payer pubkey
  to: string;             // Recipient pubkey
  amountSats: number;     // Amount in satoshis
  memo?: string;          // Optional description
  gameBreakdown?: {       // Optional per-game breakdown
    [gameName: string]: number;
  };
}

/**
 * Published settlement event (kind 36912, t: golf-result)
 * Host publishes after round completes with final net payments
 */
export interface SettlementEvent {
  roundId: string;
  courseId?: string;
  courseName?: string;
  date: number;
  hostPubkey: string;
  payments: SettlementPayment[];
  totalPot: number;
  gameModes: string[];
  eventId?: string;
  createdAt: number;
}

/**
 * Claim generated by recipient to collect winnings
 * Published as kind 36912, t: settlement-claim
 */
export interface SettlementClaim {
  settlementEventId: string;  // References original settlement event
  roundId: string;
  claimantPubkey: string;     // Recipient making the claim
  amountSats: number;         // Amount they're claiming
  invoice: string;            // Lightning invoice (bolt11)
  expiresAt: number;          // Invoice expiration timestamp
  status: 'pending' | 'paid' | 'expired' | 'cancelled';
  eventId?: string;
  createdAt: number;
}

/**
 * Payment proof published by payer after paying an invoice
 * Published as kind 36912, t: payment-proof
 */
export interface PaymentProof {
  settlementEventId: string;
  claimEventId: string;
  roundId: string;
  payerPubkey: string;
  recipientPubkey: string;
  amountSats: number;
  preimage: string;          // Payment preimage as proof
  paidAt: number;
  eventId?: string;
}

/**
 * Combined settlement view for UI display
 */
export interface SettlementView {
  settlement: SettlementEvent;
  myPayments: SettlementPayment[];     // Payments I owe
  myWinnings: SettlementPayment[];     // Payments owed to me
  claims: SettlementClaim[];           // Claims made for this settlement
  proofs: PaymentProof[];              // Payment proofs
  myNetBalance: number;                // Positive = owed to me, Negative = I owe
}

/**
 * Parse settlement event from Nostr event
 */
export function parseSettlementEvent(event: NostrEvent): SettlementEvent | null {
  try {
    // Must be APP_KIND (36912) with t: golf, t: golf-result
    const tTags = event.tags.filter(tag => tag[0] === 't');
    const hasGolf = tTags.some(tag => tag[1] === 'golf');
    const hasResult = tTags.some(tag => tag[1] === 'golf-result');
    
    if (!hasGolf || !hasResult) return null;

    const roundTag = event.tags.find(tag => tag[0] === 'round')?.[1];
    if (!roundTag) return null;

    const content = JSON.parse(event.content);
    if (!content.payments || !Array.isArray(content.payments)) return null;

    return {
      roundId: roundTag,
      courseId: content.courseId,
      courseName: content.courseName,
      date: content.date || event.created_at * 1000,
      hostPubkey: event.pubkey,
      payments: content.payments,
      totalPot: content.totalPot || 0,
      gameModes: content.gameModes || [],
      eventId: event.id,
      createdAt: event.created_at * 1000,
    };
  } catch (error) {
    console.error('Failed to parse settlement event:', error);
    return null;
  }
}

/**
 * Parse settlement claim from Nostr event
 */
export function parseSettlementClaim(event: NostrEvent): SettlementClaim | null {
  try {
    const tTags = event.tags.filter(tag => tag[0] === 't');
    const hasClaim = tTags.some(tag => tag[1] === 'settlement-claim');
    
    if (!hasClaim) return null;

    const settlementTag = event.tags.find(tag => tag[0] === 'e')?.[1]; // References settlement event
    const roundTag = event.tags.find(tag => tag[0] === 'round')?.[1];
    
    if (!settlementTag || !roundTag) return null;

    const content = JSON.parse(event.content);
    
    return {
      settlementEventId: settlementTag,
      roundId: roundTag,
      claimantPubkey: event.pubkey,
      amountSats: content.amountSats,
      invoice: content.invoice,
      expiresAt: content.expiresAt,
      status: content.status || 'pending',
      eventId: event.id,
      createdAt: event.created_at * 1000,
    };
  } catch (error) {
    console.error('Failed to parse settlement claim:', error);
    return null;
  }
}

/**
 * Parse payment proof from Nostr event
 */
export function parsePaymentProof(event: NostrEvent): PaymentProof | null {
  try {
    const tTags = event.tags.filter(tag => tag[0] === 't');
    const hasProof = tTags.some(tag => tag[1] === 'payment-proof');
    
    if (!hasProof) return null;

    const settlementTag = event.tags.find(tag => tag[0] === 'e' && tag[3] === 'settlement')?.[1];
    const claimTag = event.tags.find(tag => tag[0] === 'e' && tag[3] === 'claim')?.[1];
    const roundTag = event.tags.find(tag => tag[0] === 'round')?.[1];
    const recipientTag = event.tags.find(tag => tag[0] === 'p')?.[1];
    
    if (!settlementTag || !claimTag || !roundTag || !recipientTag) return null;

    const content = JSON.parse(event.content);
    
    return {
      settlementEventId: settlementTag,
      claimEventId: claimTag,
      roundId: roundTag,
      payerPubkey: event.pubkey,
      recipientPubkey: recipientTag,
      amountSats: content.amountSats,
      preimage: content.preimage,
      paidAt: content.paidAt || event.created_at * 1000,
      eventId: event.id,
    };
  } catch (error) {
    console.error('Failed to parse payment proof:', error);
    return null;
  }
}

/**
 * Calculate net balance for a user from a settlement
 */
export function calculateNetBalance(settlement: SettlementEvent, userPubkey: string): number {
  let balance = 0;
  
  for (const payment of settlement.payments) {
    if (payment.to === userPubkey) {
      balance += payment.amountSats;
    }
    if (payment.from === userPubkey) {
      balance -= payment.amountSats;
    }
  }
  
  return balance;
}

/**
 * Get payments a user owes
 */
export function getPaymentsOwed(settlement: SettlementEvent, userPubkey: string): SettlementPayment[] {
  return settlement.payments.filter(p => p.from === userPubkey);
}

/**
 * Get payments owed to a user
 */
export function getPaymentsOwedTo(settlement: SettlementEvent, userPubkey: string): SettlementPayment[] {
  return settlement.payments.filter(p => p.to === userPubkey);
}
